### ISSUE TITLE
Can't display border if mode is RGBA and using mask

### ISSUE THREAD

**Issue by rdelassus** [amueller/word_cloud#501]
#### Description
Can't display border if mode is RGBA

#### Steps/Code to Reproduce

Example:
```python
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt
from wordcloud import WordCloud
a = 'this is a wordcloud show test'
mask_path = "my_mask.png"
zone_mask = np.array(Image.open(mask_path))
wc = WordCloud(mode="RGBA", background_color=(0,0,0,0), contour_width=1, contour_color="black", mask=zone_mask).generate(a)
wc.to_file('wc.png')
plt.imshow(wc)
plt.axis('off')
plt.savefig('plt.png')
```

#### Expected Results
word cloud in mask with transparent background and black contour

#### Actual Results
```ValueError                                Traceback (most recent call last)
<ipython-input-67-67708b1987aa> in <module>
      7 zone_mask = np.array(Image.open(mask_path))
      8 wc = WordCloud(mode="RGBA", background_color=(0,0,0,0), contour_width=1, contour_color="black", mask=zone_mask).generate(a)
----> 9 wc.to_file('wc.png')
     10 plt.imshow(wc)
     11 plt.axis('off')

/opt/conda/envs/lucie/lib/python3.7/site-packages/wordcloud/wordcloud.py in to_file(self, filename)
    689         """
    690 
--> 691         img = self.to_image()
    692         img.save(filename, optimize=True)
    693         return self

/opt/conda/envs/lucie/lib/python3.7/site-packages/wordcloud/wordcloud.py in to_image(self)
    632             draw.text(pos, word, fill=color, font=transposed_font)
    633 
--> 634         return self._draw_contour(img=img)
    635 
    636     def recolor(self, random_state=None, color_func=None, colormap=None):

/opt/conda/envs/lucie/lib/python3.7/site-packages/wordcloud/wordcloud.py in _draw_contour(self, img)
    753 
    754         # color the contour
--> 755         ret = np.array(img) * np.invert(contour)
    756         if self.contour_color != 'black':
    757             color = Image.new(img.mode, img.size, self.contour_color)

ValueError: operands could not be broadcast together with shapes (450,450,4) (450,450,3) ```

#### Versions
<!--
Please run the following snippet and paste the output below.
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import matplotlib; print("matplotlib", matplotlib.__version__)
import wordcloud; print("wordcoud", wordcloud.__version__)
-->


<!-- Thanks for contributing! -->

**Comment by amueller** [comment]
Thanks for reporting. Do you want to send a PR to fix it?

**Comment by amueller** [comment]
this is fixed by #441 right?

**Comment by DannyBen** [comment]
I hope this can still be fixed, as far as I can understand, it is still an issue.

Reproducible with:

```
$ wordcloud_cli \
  --text mytext.txt \
  --imagefile wordcloud.png \
  --contour_width 3 \
  --contour_color 'steelblue' \
  --mask alice.png \
  --mode RGBA
```

With `--mode RGBA` it works.

I am not a python developer, so cannot help with the code I'm afraid.

**Comment by tirth78** [comment]
I would like to work on this issue. I am a Masters student in BITS Pilani. It would be really helpful if I could get some kind of approval from the owner/author.

**Comment by caioems** [comment]
This issue persists, has anyone found a workaround?

**Comment by chaseleif** [comment]
I was able to duplicate the issue using the command given by DannyBen and I submmitted a pull request with a solution.
@caioems, if you still need a workaround you can copy my changes and test it out.

**Comment by Mubashiropeyemi** [comment]
good day all
I will need assistance with coding for weather prediction(heatwave)
What is the data that may be needed? Which code system is the best?
